FROM golang:1.17-bullseye

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download -json && go mod verify

COPY main.go .
COPY cmd ./cmd
COPY define ./define
COPY exporters ./exporters
ONBUILD ARG BENCH
ONBUILD COPY benchmarks/${BENCH} ./benchmarks/${BENCH}
ONBUILD RUN go build -tags ${BENCH} -v -o . ./... 
